// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/success": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/success";
  };
  "pages/LandingPage.tsx": {
    id: "pages/LandingPage";
    page: "/";
  };
  "pages/AboutPage.tsx": {
    id: "pages/AboutPage";
    page: "/about";
  };
  "pages/SuccessPage.tsx": {
    id: "pages/SuccessPage";
    page: "/success";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/LandingPage": typeof import("./app/pages/LandingPage.tsx");
  "pages/AboutPage": typeof import("./app/pages/AboutPage.tsx");
  "pages/SuccessPage": typeof import("./app/pages/SuccessPage.tsx");
};